# Pandas 특강 5 - 누락, 중복 data 처리

In [1]:
import pandas as pd

아래 셀을 실행하기 전에 'titanic.csv' 파일을 이 ipynb 파일과 같은 폴더에 넣으셔야 합니다.

In [2]:
df = pd.read_csv('titanic.csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q
891,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S

눈에 보기에 NaN(None값, 누락 data)값이 바로 보입니다.

그리고 중복 data도 보입니다.

#### 대부분의 data가 이렇게 누락, 중복 data가 존재하니 이를 확인하고 처리할 줄 알아야 합니다.

---------

# 5. 누락, 중복 data 처리

--------

## 1) 누락 data 확인

### 1> .info()

- DataFrame에 대한 요약 정보가 담겨 있으며

- 한 번에 null의 개수를 확인할 수 있습니다.

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  892 non-null    int64
 1   Survived     892 non-null    int64
 2   Pclass       892 non-null    int64
 3   Name         892 non-null    object
 4   Sex          892 non-null    object
 5   Age          715 non-null    float64
 6   SibSp        892 non-null    int64
 7   Parch        892 non-null    int64
 8   Ticket       892 non-null    object
 9   Fare         892 non-null    float64
 10  Cabin        205 non-null    object
 11  Embarked     890 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.8+ KB

Age, Cabin, Embarked에 null값이 존재하는 걸 확인할 수 있습니다.

### 2> .isna(), .notna()

#### 누락 data를 찾는 직접적인 방법이며, 전체 DataFrame을 출력합니다. (요약적이지는 않습니다.)

- isna(): 누락 data에서 True를 반환 (== isnull() )

- notna(): 누락 data에서 False를 반환 (== notnull() )

In [4]:
df.isna()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
887,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,False,False,True,False,False,False,False,True,False
889,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,True,False
891,False,False,False,False,False,False,False,False,False,False,False,False

------

## 2) 누락 data 채워 넣기 (fillna)

### 1> 0으로 채워 넣기

In [5]:
df_fill_0 = df.fillna(0)
df_fill_0.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  892 non-null    int64
 1   Survived     892 non-null    int64
 2   Pclass       892 non-null    int64
 3   Name         892 non-null    object
 4   Sex          892 non-null    object
 5   Age          892 non-null    float64
 6   SibSp        892 non-null    int64
 7   Parch        892 non-null    int64
 8   Ticket       892 non-null    object
 9   Fare         892 non-null    float64
 10  Cabin        892 non-null    object
 11  Embarked     892 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.8+ KB

### 2> 다르게 채워 넣기

In [6]:
import numpy as np

In [7]:
each = {'Age':np.mean(df.Age), 'Embarked':0 }
df_fill_each = df.fillna(value = each)
df_fill_each.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  892 non-null    int64
 1   Survived     892 non-null    int64
 2   Pclass       892 non-null    int64
 3   Name         892 non-null    object
 4   Sex          892 non-null    object
 5   Age          892 non-null    float64
 6   SibSp        892 non-null    int64
 7   Parch        892 non-null    int64
 8   Ticket       892 non-null    object
 9   Fare         892 non-null    float64
 10  Cabin        205 non-null    object
 11  Embarked     892 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.8+ KB

### 3> 누락 column 제거

In [8]:
df.drop('Cabin', axis=1)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q
891,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S

------

## 3) 중복 data 확인 (duplicated)

In [9]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
887    False
888    False
889    False
890    False
891     True
Length: 892, dtype: bool

In [10]:
df[df.duplicated()]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
891,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1,C123,S

-------

## 4) 중복 data 제거 (drop_duplicates)

In [11]:
df_remove_dup = df.drop_duplicates()
df_remove_dup

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [12]:
df_remove_dup[df_remove_dup.duplicated()]

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []