# Pandas 특강 3 - Indexing & Slicing

In [1]:
import pandas as pd

------

# 3. Indexing & Slicing

-------

# 1) 행

- ndarray처럼 df[행, 열] 방식으로 indexing과 slicing이 불가능합니다.

- <font color="red"> loc(location의 약자) 혹은 iloc(integer location의 약자)를 사용해야합니다.

## 1-1) loc

#### index가 정수형(integer)가 아닌 경우에 사용

- df.loc를 쓰게 되면 ndarray indexing & slicing 사용하듯 쓸 수 있습니다.

- 다른 점은 <font color="red">'[start:end]= start이상 end이하'</font>가 된다는 점입니다.

## 1-2) iloc

#### index가 정수형인 경우에 사용한다.

- 나머지 사용법은 loc와 유사합니다.

In [2]:
dic4 = {'age': [20,24,27], 'orgin': ['Germany', 'China', 'Korea'], 'major':['computer science', 'math', 'economics']}
df4 = pd.DataFrame(data = dic4, index = ['Harry', 'Linda', 'Kim'] )
df4

       age    orgin             major
Harry   20  Germany  computer science
Linda   24    China              math
Kim     27    Korea         economics

### 1> Indexing

> #### 1-1> 1개 Indexing (Series로 출력)

In [3]:
df4.loc['Harry']

age                    20
orgin             Germany
major    computer science
Name: Harry, dtype: object

#### cf> 만약 Harry의 data와 Linda의 data를 모두 가져오려면?

이건 안 됩니다.

In [4]:
# 이건 numpy에서도 error

df4.loc['Harry', 'Linda']

KeyError: 'Linda'

> #### 1-2> 1개 Indexing (DataFrame으로 출력) [fancy indexing]

In [5]:
df4.loc[['Harry']]

       age    orgin             major
Harry   20  Germany  computer science

> #### 1-3> n개 Indexing (DataFrame으로 출력) [fancy indexing]

In [6]:
df4.loc[['Harry', 'Linda']]

       age    orgin             major
Harry   20  Germany  computer science
Linda   24    China              math

불편하게 fancy indexing을 쓰지 말고 slicing을 배워보겠습니다.

### 2> Slicing

- df.loc를 쓰게 되면 ndarray indexing & slicing 사용하듯 쓸 수 있습니다.

- 다른 점은 <font color="red">'[start:end]= start이상 end이하'</font>가 된다는 점입니다.

In [7]:
df4.loc['Harry':'Kim']

       age    orgin             major
Harry   20  Germany  computer science
Linda   24    China              math
Kim     27    Korea         economics

In [8]:
df4.loc['Linda':'Kim', 'age':'orgin']

       age  orgin
Linda   24  China
Kim     27  Korea

### cf> 예외사항

In [9]:
df4[0:1]

       age    orgin             major
Harry   20  Germany  computer science

-----

## 2) 열

- DataFrame에서 하나의 column(열)은 series입니다.

- <font color="red"> column의 name으로 indexing & slicing 한다.

In [10]:
URL = './heart.csv'
df = pd.read_csv(URL)
df.head() # 위의 5개 행만 slicing

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

### 1> Indexing
> #### 1-1> 1개 Indexing (Series로 출력)

In [11]:
# 1번

df['chol']

0      233
1      250
2      204
3      236
4      354
      ...
298    241
299    264
300    193
301    131
302    236
Name: chol, Length: 303, dtype: int64

In [12]:
# 2번
 
df.chol

0      233
1      250
2      204
3      236
4      354
      ...
298    241
299    264
300    193
301    131
302    236
Name: chol, Length: 303, dtype: int64

> #### 1-2> 1개 Indexing (DataFrame으로 출력) [fancy indexing]

In [13]:
df[['chol']]

     chol
0     233
1     250
2     204
3     236
4     354
..    ...
298   241
299   264
300   193
301   131
302   236

[303 rows x 1 columns]

> #### 1-3> n개 Indexing (DataFrame으로 출력) [fancy indexing]

In [14]:
df[['chol', 'age']]

     chol  age
0     233   63
1     250   37
2     204   41
3     236   56
4     354   57
..    ...  ...
298   241   57
299   264   45
300   193   68
301   131   57
302   236   57

[303 rows x 2 columns]

### 2> Slicing

In [15]:
df['cp':'ca'] # column이 행 부분을 의미하는 것이 아니므로 아래처럼 slicing을 해야합니다.

TypeError: cannot do slice indexing on RangeIndex with these indexers [cp] of type str

In [16]:
df.loc[:, 'cp':'ca']

     cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  ca
0     3       145   233    1        0      150      0      2.3      0   0
1     2       130   250    0        1      187      0      3.5      0   0
2     1       130   204    0        0      172      0      1.4      2   0
3     1       120   236    0        1      178      0      0.8      2   0
4     0       120   354    0        1      163      1      0.6      2   0
..   ..       ...   ...  ...      ...      ...    ...      ...    ...  ..
298   0       140   241    0        1      123      1      0.2      1   0
299   3       110   264    0        1      132      0      1.2      1   0
300   0       144   193    1        1      141      0      3.4      1   2
301   0       130   131    0        1      115      1      1.2      1   1
302   1       130   236    0        0      174      0      0.0      1   1

[303 rows x 10 columns]

---------

## 3) Boolean Indexing

In [17]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [18]:
df['age']>40

0       True
1      False
2       True
3       True
4       True
       ...
298     True
299     True
300     True
301     True
302     True
Name: age, Length: 303, dtype: bool

In [19]:
df[df.age>40]

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
5,57,1,0,140,192,0,1,148,0,0.4,1,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [20]:
df[(df.age>40) & (df.target == 1)]

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
5,57,1,0,140,192,0,1,148,0,0.4,1,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158,58,1,1,125,220,0,1,144,0,0.4,1,4,3,1
159,56,1,1,130,221,0,0,163,0,0.0,2,0,3,1
160,56,1,1,120,240,0,1,169,0,0.0,0,0,2,1
161,55,0,1,132,342,0,1,166,0,1.2,2,0,2,1
162,41,1,1,120,157,0,1,182,0,0.0,2,0,2,1